### ISSUE TITLE
Add netstandard2.0 as a target

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#110]
**Problem:**
When installing the SDK, user can sometimes get this:
![microsoftteams-image](https://user-images.githubusercontent.com/9810625/40051002-826bab4a-5839-11e8-9804-0d6aa2a11863.png)
There are too many package dependencies. We try to reduce the number of references to the necessary minimum.

The root cause is actually targeting netstandard1.3: https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies. In [CM Helpers SDK](https://www.nuget.org/packages/KenticoCloud.ContentManagement.Helpers/) we're using netstandard2.0 + net45 targets and there's no such issue.

**Here's a recommendation from David Fowler:**
https://twitter.com/davidfowl/status/1008453902058917888

> I know we said target The lowest netstandard but we really want everyone to re-baseline at  netstandard 2.0. At the very least add a netstandard 2.0 target.

Other services use the same [approach](https://github.com/keenlabs/keen-sdk-net/blob/master/Keen/Keen.csproj) as well.

**Solution:**
- add netstandard2.0 target to reduce the dependency footprint of the SDK.

Additional steps we can take to reduce the dependency footprint are described in #117.

**Comment by PeterSkoda** [comment]
I believe the root cause is actually because of targetting netstandard1.3, not because of net45 moniker. It is also mentioned here as well: https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies. In [CM Helpers SDK](https://www.nuget.org/packages/KenticoCloud.ContentManagement.Helpers/) we're using netstandard2.0 + net45 targets and there's no such issue (long list of dependencies) -

**Comment by petrsvihlik** [comment]
Here's a recommendation from David Fowler:
https://twitter.com/davidfowl/status/1008453902058917888

> I know we said target The lowest netstandard but we really want everyone to re-baseline at  netstandard 2.0. At the very least add a netstandard 2.0 target.

Let's add netstandard2.0 target then.
