### ISSUE TITLE
Code First approach

### ISSUE THREAD

**Issue by sjroesink** [Kentico/delivery-sdk-net#152]
The [wiki page describing how to work with strong typed models](https://github.com/Kentico/delivery-sdk-net/wiki/Working-with-Strongly-Typed-Models-(aka-Code-First-Approach)), states that it's also known as the "code first approach". Reading this made me think that the models you define in code are leading (just like Entity Framework's code first). This however doesn't seem to be the case since the content types always have to be defined via the Kentico Cloud UI.

I would suggest changing the title because I think it's not really code-first. It would be a nice feature to create the content types based on the code though!

**Comment by petrsvihlik** [comment]
These are definitely valid points!
Naming is hard and "code-first" was probably the best we were able to come up with at that time. I agree that we could rename it at some point in the future. Ideally when the time will come and it'll be necessary to raise the major version number because this will be a breaking change as well.

Do you have a better name in mind? One that could be used for all these classes (https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/CodeFirst)?

Regarding the generation of content types based on code, I'm open to any suggestions. Technically, it should be possible now with the new support of [inserting content types via the CM API](https://developer.kenticocloud.com/v1/reference#content-management-api-v2-add-content-type). What was your idea about that? A VS/VS Code plugin or something different?

Thx @sjroesink for your comments so far!

**Comment by sjroesink** [comment]
Agreed that naming can be hard, but code-first is probably confusing for people who know the term from Entity Framework.
Maybe just name it _StrongTyped_?

A relatively simple way of generating the content types could be an method in IDeliveryClient, something like `Task<bool> GenerateContentTypesAsync(params Type[] types)`. But this doesn't give the developer any control over migrations. You might want to look at how Entity Framework does this for it's code-first approach.

**Comment by Simply007** [comment]
Lets ping @jancerman + @juraju-kentico to get their opinion.

**Comment by petrsvihlik** [comment]
@Simply007  it's not only about docs. It's in the code as well...

**Comment by juraju-kentico** [comment]
I agree that "Code-first" is probably confusing and should be reserved for the practice of actually keeping/defining your models in JSON and inserting them to KC projects using the CM API v2. We can remove the "code first" references from docs quite easily once we decide to do so.

**Comment by petrsvihlik** [comment]
ok @juraju-kentico, let's adjust:
- [ ] https://developer.kenticocloud.com/docs
- [ ] https://github.com/Kentico/delivery-sdk-net/wiki
- [ ] blogs (e.g. https://kenticocloud.com/blog/what-s-new-in-kentico-cloud-march-2017)

and leave this issue open. We'll then adjust:
- [ ] the code

**Comment by juraju-kentico** [comment]
Removed occurrences of "code-first" in Wiki and DevHub. I don't have access to the blogs, that might need to be changed through Marketing. I'll investigate.

**Comment by petrsvihlik** [comment]
please do. thx @juraju-kentico

**Comment by juraju-kentico** [comment]
Created a marketing content ticket: https://kentico.atlassian.net/servicedesk/customer/portal/18/WPSD-2854

Searching the KC blog gives no other results for "code-first" occurrences.

**Comment by petrsvihlik** [comment]
Share the ticket with me, pls.

**Comment by petrsvihlik** [comment]
@PetrSvirak @matus12 could you guys please take care of this?

**Comment by matus12** [comment]
I'm on it.

**Comment by petrsvihlik** [comment]
@matus12 regarding the naming convention, I'd just omit the `CodeFirst` part for classes and .cs files and rename the [folder](https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/CodeFirst) to StrongTyping

**Comment by matus12** [comment]
There is a pull request with desired changes, I have also updated wiki files but only locally, I can replace it when the code gets released.

**Comment by petrsvihlik** [comment]
Could you please replace the docs?

**Comment by matus12** [comment]
Done.
