### ISSUE TITLE
.NET SDK ignore case when using filtering parameters

### ISSUE THREAD

**Issue by Argorob** [Kentico/delivery-sdk-net#159]
### Brief bug description

When a user fills out a form field on our site.  We use that value in our .NET SDK ContainsFilter to look for that value. But the ContainsFilter and EqualsFilter is case sensitive.   For example the form field is asking for a city.  The users inputs pensacola.  We then use that value (locationValue) into our response  `new ContainsFilter("elements.city", locationValue.Trim())`.  The KC SDK is looking for "pensacola" but we do not get results because the text field in KC contains "Pensacola".

### Expected behavior

Correct behavior is that ContainsFilter and EqualsFilter should be able to check for text and ignore case.
### Test environment

 - Platform/OS: .NET 4.61
 - Browser All browsers

**Comment by PetrSvirak** [comment]
Hi @Argorob.

Thank you for pointing this issue out.

I've briefly looked into it and I'm afraid that you have stumbled upon limitations of current `Delivery API`. There is, unfortunately, no way a single SDK can sort this out since it is the `API` itself that is designed with code names and identifiers rather than text search and loose equality in mind. Since this is the `Delivery API` feature that is missing here, please, consider submitting the [idea for our product roadmap](https://portal.productboard.com/kenticocloud).

I would also like to point out one more thing. You used `ContainsFilter` with the `elements.city` field that seems to be a plain string value in your code sample. This filter actually works only for array values as described in the [`ContainsFilter` class comment](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/QueryParameters/Filters/ContainsFilter.cs#L5). I believe that [`EqualsFilter`](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/QueryParameters/Filters/EqualsFilter.cs) is actually the only option here since [`Delivery API`](https://developer.kenticocloud.com/reference#section-filtering-operators) does not support partial matching right now. I found [an article](https://kenticocloud.com/blog/getting-to-know-the-kentico-cloud-net-sdk-deliver) that suggests otherwise and it is currenly being reviewed to prevent any confusion.

We will also look further into your issue and try to come with some potential workaround(s) that might solve this particular situation.

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a month since the last update here.

If we missed anything on this issue or if you want to keep it open, please reply here. 

Thanks for being a part of the Kentico community!
