### ISSUE TITLE
In the Pagination when retrieving lists of content items it should give either total available items or total available pages

### ISSUE THREAD

**Issue by hades200082** [Kentico/delivery-sdk-net#52]
If I want to implement traditional pagination on my site/app I need to be able to find out how many total items there are available in the result set without paging, but only retrieve the current page's items.

The Pagination object seems to be the right place for this but it doesn't seem to work like this, instead only returning the number of items currently retrieved which is the single page worth.

**Comment by petrsvihlik** [comment]
Seems valid to me. Currently, you have to make an extra request to get the `count`.

[The documentation says](https://developer.kenticocloud.com/v1/reference#listing-responses):

> If the limit and skip query parameters aren't set, the `count` attribute will contain the total number of content items matching the filtering parameters.

@tomashruby @alesk-kentico What is the idea behind this? Is this how users are supposed to calculate the number of pages and render classic pagination?

**Comment by hades200082** [comment]
Doubling the number of api calls required seems bad. This is a cost metric after all. 

Also, if the result set is large it could become a performance issue to bring all that data back

**Comment by petrsvihlik** [comment]
You could [limit](https://developer.kenticocloud.com/v1/reference#projection) the amount of data coming back from the endpoint...that shouldn't be an issue. However, I agree making a separate request just to get the pagination data seems kind of redundant. Let's wait for some comments from the internal teams.

**Comment by alesk-kentico** [comment]
Delivery API has been designed with only one scenario in mind – navigating through a large set of content items sequentially. The idea is simple. When a web site visitor requests content, only the first page is displayed. If it does not contain relevant content, they can navigate to the next page.

The need to go to the specific page might suggest that the search capabilities are limited and users are forced to find the right page in the listing. Also, calculating the total number of content items that match the specified query is very expensive operation. This, combined with the fact that the number is often discarded, makes it a feature that needs more feedback. Could you please elaborate more on your need to find out the total number of content items?

There is currently a workaround, but it requires retrieving a list of all content items. You might use projection to reduce the response size. Unfortunately, you still need to send two requests. Alternatively, you can retrieve all content items and do paging locally, but it depends on your requirements.

**Comment by kenticomartinh** [comment]
@alesk-kentico Based on your assumption, Google shouldn't provide traditional paging because they have very good filtering options, yet they do ... https://www.google.cz/#q=headless+cms&start=70

Here is "why" I need it from the point of the site visitor ... I use a filter, and after that I want to scan through the results page-by-page, but I want to know whether the current results are 20 or 20k in order to decide whether it is worth it to scan them manually, or if I need to further restrict the filter to get amount that is even possible to browse through. So the number of total items (even if it would be a rough estimate) is important for good UX even in case you use continuous paging.

I guess if the problem for the client is the number of API calls, and if it is most often not used, it could be an optional parameter of the query, by default false.

In the case I outlined I would make the first call (the most often call on my site) with getting the total number, and the subsequent calls just for the pages, as the total number would be already known.

**Comment by alesk-kentico** [comment]
Thank you for your feedback. However, I'm not sure I follow your argument. My only assumption was that there might have been another approach that does not require pagination. Also, I do not know why Google supports pagination, but I can come up with many reasons, e.g. displaying more ads.

**Comment by kenticomartinh** [comment]
@alesk-kentico the scenario I outlined does not require pagination, does at least that make sense to you?

**Comment by alesk-kentico** [comment]
Yes, it does and I'm grateful for your feedback.

**Comment by petrsvihlik** [comment]
Since this feedback relates to KC Delivery endpoint rather than to this SDK, I'm forwarding it to our Product Owners and closing the issue.

If the endpoint should get updated in the future, we'll make sure to reflect the changes in the SDK.
