### ISSUE TITLE
Improve pagination in the DeliveryItemListingResponse

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/delivery-sdk-net#64]
As part of the DeliveryItemListingResponse object, the Pagination.NextPageUrl property provides a reference to getting the next page data.

The GetItemsAsync method should have an overload to be able to get the next page data, either using the NextPageUrl, or something more appropriate.

**Comment by petrsvihlik** [comment]
- What do you mean by "something more appropriate"? 

BTW - I think the `next_page` attribute in the response is there mainly for JS consumers. In client-server apps, you typically pass (or keep) the state (`skip`, `limit`, `cout`) to backend so that you can construct a new request. Passing the whole URL doesn't seem very clean to me.
Can you suggest any scenarios where it make sense to use such an approach?

**Comment by petrsvihlik** [comment]
ping @JanLenoch

**Comment by JanLenoch** [comment]
Sorry, I had completely missed your reply.

By stating "more appropriate", I'd been thinking of the more granular `skip`, `limit` (and eventually the `count`) parameter values, rather than the compiled URL.

You're right, in client-server apps, the backend may keep track of the paging using these granular values, without any special treatment in the GetItemsAsync.

Closing.
