### ISSUE TITLE
Spike: Simplify IDeliveryClient and get rid of its internal dependencies/references

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#87]
### Motivation

- `IDeliveryClient` contains members such as `IContentLinkUrlResolver`, `ICodeFirstModelProvider`, or `IInlineContentItemsProcessor` which shouldn't be part of the contract at all. Currently, they're there just because of internal referencing of the `DeliveryClient` in the underlying code.
- The wrong code can be easily identified:
  - All references to `this` in the `DeliveryClient` (and references to `IDeliveryClient` in the underlying code 
    - such as `_contentLinkResolver = new ContentLinkResolver(_client.ContentLinkUrlResolver);` in the  `ContentItem`.
    - or `_client.CodeFirstModelProvider.GetContentItemModel<T>(source, _response["modular_content"]))` in `DeliveryItemListingResponse<T>`

### Expected spike outcome

We should come up with a way to get rid of these dependencies and simplify the `IDeliveryClient` contract.

Things to consider:
- we could utilize DI, however we'd like to avoid using any particular DI framework
  - we don't want to push consumers of the library to use a specific DI framework
  - we might want to introduce some simple DI of our own making, crafted just to fit our needs
    - there would be a default implementation of the container with a possibility to replace the logic
    - it should also be possible to inject a DI framework of user's choice to take care of the instantiation completely
      - is there some kind of generic DI interface that we could expose for replacement?
  - we should keep in mind that the user can create multiple instances of the `DeliveryClient` in a single application. So a **simple** singleton might not be the right thing for us.
- another approach would be to refactor the logic in a way that no DI is needed. 
  - in a way that all the complex stuff happens outside of the models/response objects and the models/responses are just dummy container objects

**Comment by JanLenoch** [comment]
Wouldn't it be better to use the [IServiceCollection](https://github.com/Kentico/delivery-sdk-net/issues/61) contract instead of writing our own DI, @petrsvihlik ?

**Comment by petrsvihlik** [comment]
Using `IServiceCollection` is one of the possible ways of ensuring that you can inject a DI framework of your choice. But we shouldn't break the compatibility for those who don't use a DI FW. In other words, the SDK should keep working even if we introduce IoC. Therefore, I thought we might need to have some basic implementation.

**Comment by matus12** [comment]
What we have found out so far:

- we have refactored the solution in 9bff0c0 so that DeliveryClient is no longer passed to the underlying code, which was then used to access its properties
- dependency injection might be solved with IServiceCollection, where we created an [extension method](https://github.com/Kentico/delivery-sdk-net/commit/31abea252bcf801ccd5dfb064408ac64b60991b2) AddDeliveryClient, which registers its inner dependencies and returns a DeliveryClient instance; [supported versions of .NET](http://immo.landwerth.net/netstandard-versions/#)
- in .NET Core users create/edit appsettings.json file where they add DeliveryOptions, register them in Startup.cs by adding
`services.Configure<DeliveryOptions>(Configuration.GetSection("DeliveryOptions"));`
which are then retrieved in the AddDeliveryClient extension method

- in .NET Framework users may do the same like [this](https://stackoverflow.com/questions/49572079/net-core-dependency-injection-backwards-compatibility-with-net-framework/49573845#49573845)
- users that don't use DI can use either constructors as before, or use a [builder class](https://github.com/Kentico/delivery-sdk-net/commit/a4276da3fa46a82193b8bc63dec3f2898ffc6af3) for creating the DeliveryClient
- using OWIN, customer will need to introduce resolver and implement the DI logic in the similar way as [here](https://gist.github.com/andriybuday/a96bfc7845ba1514561a4e6f146a629d)
